export const images = [
  'users-see-pixels',
  'users-see-pixels-ukr',
  'adam-of-all',
  'object-adam',
  'funcs-rule',
  'reference-is-a-lockpick',
  'reference-is-a-lockpick-ukr',
  'arrow-funcs-neutered-kitties-ukr',
  'arrow-funcs-neutered-kitties',
  'object-constructor',
  'object-constructor-ukr',
  'funcs-are-our-jam',
  'funcs-are-our-jam-ukr',
  'function-balls',
  'function-balls-ukr',
]

export const slogans = [
  'Users see pixels, front-enders - spot tags, but devs, man, they`re all about objects',
  "Юзер бачить ​пікселі, ​верстальник -​теги, а дев - об'єкти",
  'All comes from the Object which is Adam of all',
  'Все походить від Object, який є Адамом усього',
  'Funcs totally rule!',
  'Reference is a lockpick',
  'Посилання - це відмичка',
  'Стрілочні ​функції - це​ кастровані​ котики',
  'Arrow functions are neutered kitties',
  'See an object, look for constructor',
  "Бачиш об'єкт - шукай конструктор",
  'Funcs are our jam!',
  'Функції - ​це наше все!',
  'Only funcs have the balls',
  'Тільки у ​функції ​є balls',
]
